version: "3.8"

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - laravel

    web:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: SoftIdea
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
            UPLOAD_LIMIT: 100M
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:

